FROM allomov/ubuntu
MAINTAINER Alex Lomov <lomov.as@gmail.com>

# Install Java 7
RUN DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --force-yes \
    openjdk-7-jre-headless

# Define default command
CMD ["bash"]
